name: UntitledDuelsPlugin
version: '${project.version}'
main: me.diffusehyperion.untitledduelsplugin.UntitledDuelsPlugin
api-version: 1.19
load: POSTWORLD
libraries:
  - commons-io:commons-io:2.11.0
commands:
  arenas:
    usage: /arena (create/join/set/add)
  stats:
    usage: /stats (wins/loses) (player)
  1v1:
    usage: /1v1 (player)
  kits:
    usage: /kits (create/delete/list)
  lobby:
    usage: /lobby (set/tp)
